Fixing NoSuchMethodError runingInTestMode() When using this plugin in a Play project the following exception is thrown at startup: Exception in thread "main" java.lang.NoSuchMethodError: play.Play.runingInTestMode() The reason is the method was renamed in 'runningInTestMode()'